### ISSUE TITLE
Request: configurable timeout to waitForGame

### ISSUE THREAD

**Issue by clckwrkbdgr** [kitten-science/kitten-scientists#177]
### Describe the Enhancement

When kittensgame is opened in background tab (I use Firefox ESR), it tends to initialize page with some delay, and Kittens Scientists cannot wait long enough and abort with message in console: "Unable to find game page. Giving up."

I have to adjust the script manually after every update to significantly increase default timeout interval:

```diff
-    static async waitForGame(timeout = 3e4) {
+    static async waitForGame(timeout = 300e4) {
```

Can this timeout value be configurable? I would be happy even with some hidden parameter in localStorage.

**Comment by oliversalzburg** [comment]
Could you explain in detail step-by-step how this happens? How would I open the game in a background tab in Firefox ESR to reproduce this?

Ideally, we find a solution that is more robust than what we currently have.

**Comment by clckwrkbdgr** [comment]
1. I just open kittensgame from web link in "separate tab" mode or open it from command line, in both cases new tab is not immediately activated and remains running in background.
   - I'm not sure what exactly controls this behavior, but I have both `browser.tabs.loadInBackground` and `browser.tabs.loadDivertedInBackground` set to true.
2. If I switch to the new tab manually immediately and I see "loading" progress bar, then after game is loaded, KS options block appears as expected.
3. But if I do it later (usually after couple of minutes; I assume 30s should be enough), game is still loaded, but KS options block is missing and there are lots of "waiting for the game" messages in console with final error: "Unable to find game page. Giving up."

I've noticed similar behavior for many websites in my browser, all of them tend to load slower in inactive tabs, especially if there are lots of tabs opened at the same time. So I'm not sure if this points to some issue with the method of detecting loaded game, most likely my workstation+browser are just awfully slow.

**Comment by oliversalzburg** [comment]
I'm reproducing this in Firefox Nightly. I have no idea how ESR might behave differently in this scenario.
- `browser.tabs.loadInBackground` is `true` by default
- `browser.tabs.loadDivertedInBackground` is `false` by default, changed to `true`

The only further change from the baseline configuration I made is, changing the Startup type to "Open previous windows and tabs"

- Because you expect KS to load when KG loads, I assume you have a userscript manager. I'm trying this with Tampermonkey and beta.6, as in <https://github.com/kitten-science/kitten-scientists/releases/download/v2.0.0-beta.6/kitten-scientists-2.0.0-beta.6.user.js>
- When I now load the game, KS is loaded after KG finishes loading, as I would expect.
- I now close Firefox, not having focus on the KG tab.
- I now reopen Firefox, and the KG tab is still not in focus, as I would expect. I now wait for a couple of minutes.
- I focus on the KG tab. The game loads. KS appears.

Can't reproduce this, but I'm happy to try more, if you can point out where my approach is not right. I'd also be willing to implement an override for the timeout. Seems like a good idea in general.

**Comment by clckwrkbdgr** [comment]
Unfortunately I have no other data except already provided. You're basically repeating my scenario except for having ESR version, I have no idea what else could affect loading sequence and don't know where to look. I appreciate the effort, but still think that the main reason is that my workstation is too slow.

**Comment by oliversalzburg** [comment]
Thanks for confirming. I'll just go with your original request then and allow extending the timeout through local means.

I'll also likely bump the timeout in general, as I don't really see how that could cause any major problems.

**Comment by oliversalzburg** [comment]
I extended the default timeout to 2 minutes. You can override it by setting `localStorage["ks.timeout"]`. This will also be documented in the **Internals** section of the documentation.

Please let me know in case this is still not working for you :)
