### ISSUE TITLE
Scatter with heat trigger

### ISSUE THREAD

**Issue by PaulWoitaschek** [kitten-science/kitten-scientists#190]
### Describe the Feature

As Void is only being generated when seasons pass, I'd like to not skip time as long as possible.
The way I would do it manually is:
* Scatter Crystals until max heat
* Wait until heat is at 0 and get some void in between
* Repeat

Currently it's not possible to do this because once we are at max heat, KS will advance the time in yearly increments and therefore void is never generated.

If the time skip feature would have a heat trigger, that would allow one to generate Void while also scattering time crystals.

**Comment by oliversalzburg** [comment]
Thanks for the clear explanation. I feel like this aligns very well with other open issues that relate to this area of automation. Let's see what we can make of this :D

**Comment by JaroslawKolmaga** [comment]
For void farm, I do use "skip only on summer" - the game would go through spring, go into void farm, skip using maximum allowed by KS and repeat. Nice and easy. That being said, I would absolutely love a "minimum heat" setting as proposed, allowing the KS to wait till heat drops to-or-below trigger point - and only skip then. Not for void farming for me - but for general stability and experience, too. As of now, I skip very often to build up as fast as possible after restart, and that means skipping 1 year (useless) every 2-3 seconds, plus the darned chronoforges...

These are a bigger issue for clean void farming I think - having them on will auto-skip 1 year before the season ends, wasting the void charge. Keeping them off and turning them on manually on the other hand means having to baby-sit the game, since KS can hardly intervene while a chronoforge stack is burning through 50000 years 5 years at a time, maxing out resources. A similar min-max on-off approach would help greatly here, I believe - turn ChF on above X% heat stored but then turn it off when it goes below 100% - allowing you to set what "stacks" of years ChF should jump in-between activation.

**Comment by oliversalzburg** [comment]
Using the new Active Heat Transfer functionality, contributed in #550, void farming should work well in combination with time skips.
