### ISSUE TITLE
Steel is not crafted if either coal or iron is below cap

### ISSUE THREAD

**Issue by andrewshyichuk** [kitten-science/kitten-scientists#342]
### Version Check

- [x] I have updated to `v2.0.0-beta.7` or later.
- [X] I have updated to the `nightly` build from last night (or latest one available).
- [x] I have tested with the latest source code from `main` as of today.

### What browser are you using?

Firefox

### How are you loading Kitten Scientists?

Userscript Manager (Tampermonkey)

### Describe the Bug

KS beta.8-20230717-b86ef52 and 2.0.0-beta.8-20231018-1fbc52c

I have a setup: coal: stock 0, consume 1; iron: stock 150K, consume 1; craft: steel (and other things); trigger 0.9.
Result: steel not crafted. I can have, say, 200-250-300K of iron, 80K coal (at cap), and steel is not crafted. Other resources are crafted correctly. 

I followed the game for some time: it triggers at iron cap, no matter the coal cap. Even worse, it apparently requires both resources to be at cap. It has to trigger at "or", not at "and".

Anything to do with allMaterialsAboveTrigger in the code maybe? 
Anyway, I think that it should trigger if any of the resources is above trigger, otherwise it kinda makes no sense.

**Comment by oliversalzburg** [comment]
> Anything to do with allMaterialsAboveTrigger in the code maybe?

Possibly. What is your trigger value for the crafting section?

[The documentation](https://kitten-science.github.io/kitten-scientists/sections/workshop/) says this about the behavior:

> Additionally, if crafting a resource requires one or more materials that have a capacity, those materials need to be filled to **Trigger** of their stock capacity.

Historically, there were hardcoded resources that the trigger would apply to for each resource to craft, ignoring any other resources required for the craft. This lead to a lot of balancing issues between stuff like plates and steel. This was solved in beta 7 by a new craft balancing mechanism. 

That being said, it's possible that it would make more sense to consider the craft if _any_ resource is above trigger. But it will require a bit of testing to see if it introduces any new issues in some parts of the game timeline.

**Comment by andrewshyichuk** [comment]
What about just adding a switch to select between the "any above trigger" and the "all above trigger" and let the user pick their poison?

**Comment by oliversalzburg** [comment]
Hmm, yeah, sounds reasonable.

**Comment by wasniahC** [comment]
> What about just adding a switch to select between the "any above trigger" and the "all above trigger" and let the user pick their poison?

It would be a good idea to implement this across the board - so that every threshold option comes with the option to check "any" or "all" of its resource reqs.

**Comment by oliversalzburg** [comment]
Yeah, should probably go hand-in-hand with #451

**Comment by MiniHerc** [comment]
Encountered this problem today. Any updates on fixing?

**Comment by oliversalzburg** [comment]
@MiniHerc Sorry, but this is an especially tough one that keeps coming up. There won't be a good solution in the foreseeable future :(

**Comment by MiniHerc** [comment]
@oliversalzburg Can't it just craft steel if coal is at 99% of cap and iron is available? That's really all I want.

**Comment by oliversalzburg** [comment]
Possibly related to #451

**Comment by oliversalzburg** [comment]
I'm actively looking at this subject yet again, to try to get _some_ progress in beta 9.

I feel like, the users that have reported this issue over the years (there were plenty), might be suffering from the horrible default settings in KS. The default trigger value for the Workshop is 95%, which suggests that a high value is good. It seems intuitive, you build/buy all the important stuff, then craft more advanced resources from the excess, right?

Over the past year, I've looked at these default values very suspiciously. Today, I believe the correct trigger is _low_, instead of high.

When we want to balance crafts in KS, the "Limited" option is the most advanced solution. When you trigger at 10%, but your crafts are limited, they will slowly scale up when the craft _actually_ becomes effective beyond the trigger value.

I remember being very hesitant to accept this idea, but it works a lot better than strategies that rely on near-cap triggers.

That being said, the subject will be investigated and worked on until we have a working solution.

**Comment by oliversalzburg** [comment]
I'm hoping that #785 will help with the pain in this scenario. I generally want to supply more granular control over crafts. I'm hoping this will be more generally useful. The "any vs all" idea definitely contributed a lot to recent developments in crafting.

In general, what was reported here, was actually working as designed. I'm hoping beta 9 will feel much different.
