### ISSUE TITLE
Individual Thresholds

### ISSUE THREAD

**Issue by wasniahC** [kitten-science/kitten-scientists#451]
### Describe the Enhancement

Currently, resource thresholds are tied to categories, while build limits are tied to individual items. For example: You can set a threshold for bonfire, and you can set build limits for maximum AI cores.

My individual thresholds proposal is this - ability to set thresholds at a more granular level, on a per-option basis. For example, crafting a hut, log house, or workshop at a threshold at 0 (So it will craft ASAP), but crafting a barn at a threshold of 0.9 (i.e. only when approaching the wood cap). This could be useful across every category where the category has a threshold for purchases - bonfire, religion, space, and time. It would also be nice for trade embassies, and for workshop crafting.

A secondary change to follow-up this one might be to add this functionality to science technologies and workshop upgrades (so they aren't just a binary "ASAP" vs "not researched")

- [x] Bonfire
- [x] Religion
- [x] Space
- [x] Time
- [ ] Technologies
- [ ] Upgrades

**Comment by oliversalzburg** [comment]
A great idea actually. Having only the single trigger often feels too limiting. 

I'd love to add this, but I don't see it happening any time soon. I feel like the implementation could be challenging from a UI perspective, especially given other open, good suggestions right now.

This also feels like it could be better covered in Kitten Engineers, where the focus will be on supporting complex rule sets, instead of the "simplicity" of KS.

We'll see where this goes, but it's obvious that we need better control sooner or later.
